### ISSUE TITLE
Melhorar README

### ISSUE THREAD

**Issue by diegotoral** [jeffersonmourak/pyTerm#3]
O README é uma das partes mais importantes de qualquer projeto open source ([ou não](http://diegotoral.me/readmes-e-projetos-privados/)), por isso acho que seria uma boa incluir algumas coisas que senti falta:
1. Usage
2. Installation

Também acho que seria interessante incluir um vídeo demonstrando a utilização do programa (além das instruções de uso em texto), pois senti isso um pouco `obscuro`.

**Comment by jeffersonmourak** [comment]
Diego, fiz algumas modificações no Read-me, em breve vou colocar um gif mostrando a utilização,
Muito obrigado por ajudar no projeto :smile:

**Comment by diegotoral** [comment]
:+1:
